import type { Tenant } from './domain';

export const sampleTenants: Tenant[] = [
  {
    id: '7d0e40b7-4b8b-4d15-a94b-100000000001',
    companyName: 'Northstar Supplies',
    slug: 'northstar-supplies',
    exactSubdomain: 'northstar-supplies.leadfinder.business',
    status: 'active',
    monitoringMode: 'shared_access',
    monitoringStatus: 'pass',
    placesKeyFingerprint: '8F3A19C2',
    googleProjectId: 'northstar-places-prod',
    websiteRestrictionStatus: 'pass',
    billingStatus: 'pass',
    placesApiStatus: 'pass',
    customerLiveStatus: 'pass',
    monthlyTarget: 1000,
    annualRevenueMyr: 1500,
    releaseVersion: 'v1.0.0',
    vercelProjectId: 'prj_sample_northstar',
    lastHealthStatus: 'green',
    createdAt: '2026-08-20T08:30:00Z',
  },
  {
    id: '7d0e40b7-4b8b-4d15-a94b-100000000002',
    companyName: 'Meridian Industrial',
    slug: 'meridian-industrial',
    exactSubdomain: 'meridian-industrial.leadfinder.business',
    status: 'verification_pending',
    monitoringMode: 'dedicated_credential',
    monitoringStatus: 'pending',
    placesKeyFingerprint: '6D91B72E',
    googleProjectId: 'meridian-leads',
    websiteRestrictionStatus: 'pending',
    billingStatus: 'pass',
    placesApiStatus: 'pass',
    customerLiveStatus: 'pending',
    monthlyTarget: 1000,
    annualRevenueMyr: 1500,
    releaseVersion: null,
    vercelProjectId: null,
    lastHealthStatus: 'amber',
    createdAt: '2026-08-22T04:15:00Z',
  },
  {
    id: '7d0e40b7-4b8b-4d15-a94b-100000000003',
    companyName: 'Atlas Commerce',
    slug: 'atlas-commerce',
    exactSubdomain: 'atlas-commerce.leadfinder.business',
    status: 'setup_pending',
    monitoringMode: 'not_configured',
    monitoringStatus: 'not_checked',
    placesKeyFingerprint: null,
    googleProjectId: null,
    websiteRestrictionStatus: 'not_checked',
    billingStatus: 'not_checked',
    placesApiStatus: 'not_checked',
    customerLiveStatus: 'not_checked',
    monthlyTarget: 1000,
    annualRevenueMyr: 1500,
    releaseVersion: null,
    vercelProjectId: null,
    lastHealthStatus: 'unknown',
    createdAt: '2026-08-23T01:00:00Z',
  },
];
